// Generated by scripts/generate-axe-rules.ts from axe-core 4.12.1. Do not edit.
// Regenerate with: pnpm --filter @ally-fix/llm grounding:generate

/** What axe-core says about one rule, and which WCAG criteria it enforces. */
export interface AxeRuleFacts {
  /** axe's one-line statement of the requirement. */
  help: string;
  /** axe's longer description of what the rule checks. */
  description: string;
  /** WCAG success criteria this rule maps to, e.g. ["1.1.1"]. Never empty. */
  criteria: string[];
}

export const AXE_CORE_VERSION = "4.12.1";

export const AXE_RULE_FACTS: Record<string, AxeRuleFacts> = {
  "area-alt": {
    help: "Active <area> elements must have alternative text",
    description: "Ensure <area> elements of image maps have alternative text",
    criteria: ["2.4.4", "4.1.2"],
  },
  "aria-allowed-attr": {
    help: "Elements must only use supported ARIA attributes",
    description: "Ensure an element's role supports its ARIA attributes",
    criteria: ["4.1.2"],
  },
  "aria-braille-equivalent": {
    help: "aria-braille attributes must have a non-braille equivalent",
    description:
      "Ensure aria-braillelabel and aria-brailleroledescription have a non-braille equivalent",
    criteria: ["4.1.2"],
  },
  "aria-command-name": {
    help: "ARIA commands must have an accessible name",
    description: "Ensure every ARIA button, link and menuitem has an accessible name",
    criteria: ["4.1.2"],
  },
  "aria-conditional-attr": {
    help: "ARIA attributes must be used as specified for the element's role",
    description:
      "Ensure ARIA attributes are used as described in the specification of the element's role",
    criteria: ["4.1.2"],
  },
  "aria-deprecated-role": {
    help: "Deprecated ARIA roles must not be used",
    description: "Ensure elements do not use deprecated roles",
    criteria: ["4.1.2"],
  },
  "aria-hidden-body": {
    help: 'aria-hidden="true" must not be present on the document body',
    description: 'Ensure aria-hidden="true" is not present on the document body.',
    criteria: ["1.3.1", "4.1.2"],
  },
  "aria-hidden-focus": {
    help: "ARIA hidden element must not be focusable or contain focusable elements",
    description: "Ensure aria-hidden elements are not focusable nor contain focusable elements",
    criteria: ["4.1.2"],
  },
  "aria-input-field-name": {
    help: "ARIA input fields must have an accessible name",
    description: "Ensure every ARIA input field has an accessible name",
    criteria: ["4.1.2"],
  },
  "aria-meter-name": {
    help: "ARIA meter nodes must have an accessible name",
    description: "Ensure every ARIA meter node has an accessible name",
    criteria: ["1.1.1"],
  },
  "aria-progressbar-name": {
    help: "ARIA progressbar nodes must have an accessible name",
    description: "Ensure every ARIA progressbar node has an accessible name",
    criteria: ["1.1.1"],
  },
  "aria-prohibited-attr": {
    help: "Elements must only use permitted ARIA attributes",
    description: "Ensure ARIA attributes are not prohibited for an element's role",
    criteria: ["4.1.2"],
  },
  "aria-required-attr": {
    help: "Required ARIA attributes must be provided",
    description: "Ensure elements with ARIA roles have all required ARIA attributes",
    criteria: ["4.1.2"],
  },
  "aria-required-children": {
    help: "Certain ARIA roles must contain particular children",
    description: "Ensure elements with an ARIA role that require child roles contain them",
    criteria: ["1.3.1"],
  },
  "aria-required-parent": {
    help: "Certain ARIA roles must be contained by particular parents",
    description:
      "Ensure elements with an ARIA role that require parent roles are contained by them",
    criteria: ["1.3.1"],
  },
  "aria-roledescription": {
    help: "aria-roledescription must be on elements with a semantic role",
    description:
      "Ensure aria-roledescription is only used on elements with an implicit or explicit role",
    criteria: ["4.1.2"],
  },
  "aria-roles": {
    help: "ARIA roles used must conform to valid values",
    description: "Ensure all elements with a role attribute use a valid value",
    criteria: ["4.1.2"],
  },
  "aria-tab-name": {
    help: "ARIA tab nodes must have an accessible name",
    description: "Ensure every ARIA tab node has an accessible name",
    criteria: ["4.1.2"],
  },
  "aria-toggle-field-name": {
    help: "ARIA toggle fields must have an accessible name",
    description: "Ensure every ARIA toggle field has an accessible name",
    criteria: ["4.1.2"],
  },
  "aria-tooltip-name": {
    help: "ARIA tooltip nodes must have an accessible name",
    description: "Ensure every ARIA tooltip node has an accessible name",
    criteria: ["4.1.2"],
  },
  "aria-valid-attr": {
    help: "ARIA attributes must conform to valid names",
    description: "Ensure attributes that begin with aria- are valid ARIA attributes",
    criteria: ["4.1.2"],
  },
  "aria-valid-attr-value": {
    help: "ARIA attributes must conform to valid values",
    description: "Ensure all ARIA attributes have valid values",
    criteria: ["4.1.2"],
  },
  "audio-caption": {
    help: "<audio> elements must have a captions track",
    description: "Ensure <audio> elements have captions",
    criteria: ["1.2.1"],
  },
  "autocomplete-valid": {
    help: "autocomplete attribute must be used correctly",
    description: "Ensure the autocomplete attribute is correct and suitable for the form field",
    criteria: ["1.3.5"],
  },
  "avoid-inline-spacing": {
    help: "Inline text spacing must be adjustable with custom stylesheets",
    description:
      "Ensure that text spacing set through style attributes can be adjusted with custom stylesheets",
    criteria: ["1.4.12"],
  },
  blink: {
    help: "<blink> elements are deprecated and must not be used",
    description: "Ensure <blink> elements are not used",
    criteria: ["2.2.2"],
  },
  "button-name": {
    help: "Buttons must have discernible text",
    description: "Ensure buttons have discernible text",
    criteria: ["4.1.2"],
  },
  bypass: {
    help: "Page must have means to bypass repeated blocks",
    description:
      "Ensure each page has at least one mechanism for a user to bypass navigation and jump straight to the content",
    criteria: ["2.4.1"],
  },
  "color-contrast": {
    help: "Elements must meet minimum color contrast ratio thresholds",
    description:
      "Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds",
    criteria: ["1.4.3"],
  },
  "color-contrast-enhanced": {
    help: "Elements must meet enhanced color contrast ratio thresholds",
    description:
      "Ensure the contrast between foreground and background colors meets WCAG 2 AAA enhanced contrast ratio thresholds",
    criteria: ["1.4.6"],
  },
  "css-orientation-lock": {
    help: "CSS Media queries must not lock display orientation",
    description:
      "Ensure content is not locked to any specific display orientation, and the content is operable in all display orientations",
    criteria: ["1.3.4"],
  },
  "definition-list": {
    help: "<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements",
    description: "Ensure <dl> elements are structured correctly",
    criteria: ["1.3.1"],
  },
  dlitem: {
    help: "<dt> and <dd> elements must be contained by a <dl>",
    description: "Ensure <dt> and <dd> elements are contained by a <dl>",
    criteria: ["1.3.1"],
  },
  "document-title": {
    help: "Documents must have <title> element to aid in navigation",
    description: "Ensure each HTML document contains a non-empty <title> element",
    criteria: ["2.4.2"],
  },
  "duplicate-id": {
    help: "id attribute value must be unique",
    description: "Ensure every id attribute value is unique",
    criteria: ["4.1.1"],
  },
  "duplicate-id-active": {
    help: "IDs of active elements must be unique",
    description: "Ensure every id attribute value of active elements is unique",
    criteria: ["4.1.1"],
  },
  "duplicate-id-aria": {
    help: "IDs used in ARIA and labels must be unique",
    description: "Ensure every id attribute value used in ARIA and in labels is unique",
    criteria: ["4.1.2"],
  },
  "form-field-multiple-labels": {
    help: "Form field must not have multiple label elements",
    description: "Ensure form field does not have multiple label elements",
    criteria: ["3.3.2"],
  },
  "frame-focusable-content": {
    help: "Frames with focusable content must not have tabindex=-1",
    description:
      "Ensure <frame> and <iframe> elements with focusable content do not have tabindex=-1",
    criteria: ["2.1.1"],
  },
  "frame-title": {
    help: "Frames must have an accessible name",
    description: "Ensure <iframe> and <frame> elements have an accessible name",
    criteria: ["4.1.2"],
  },
  "frame-title-unique": {
    help: "Frames must have a unique title attribute",
    description: "Ensure <iframe> and <frame> elements contain a unique title attribute",
    criteria: ["4.1.2"],
  },
  "html-has-lang": {
    help: "<html> element must have a lang attribute",
    description: "Ensure every HTML document has a lang attribute",
    criteria: ["3.1.1"],
  },
  "html-lang-valid": {
    help: "<html> element must have a valid value for the lang attribute",
    description: "Ensure the lang attribute of the <html> element has a valid value",
    criteria: ["3.1.1"],
  },
  "html-xml-lang-mismatch": {
    help: "HTML elements with lang and xml:lang must have the same base language",
    description:
      "Ensure that HTML elements with both valid lang and xml:lang attributes agree on the base language of the page",
    criteria: ["3.1.1"],
  },
  "identical-links-same-purpose": {
    help: "Links with the same name must have a similar purpose",
    description: "Ensure that links with the same accessible name serve a similar purpose",
    criteria: ["2.4.9"],
  },
  "image-alt": {
    help: "Images must have alternative text",
    description: "Ensure <img> elements have alternative text or a role of none or presentation",
    criteria: ["1.1.1"],
  },
  "input-button-name": {
    help: "Input buttons must have discernible text",
    description: "Ensure input buttons have discernible text",
    criteria: ["4.1.2"],
  },
  "input-image-alt": {
    help: "Image buttons must have alternative text",
    description: 'Ensure <input type="image"> elements have alternative text',
    criteria: ["1.1.1", "4.1.2"],
  },
  label: {
    help: "Form elements must have labels",
    description: "Ensure every form element has a label",
    criteria: ["4.1.2"],
  },
  "label-content-name-mismatch": {
    help: "Elements must have their visible text as part of their accessible name",
    description:
      "Ensure that elements labelled through their content must have their visible text as part of their accessible name",
    criteria: ["2.5.3"],
  },
  "link-in-text-block": {
    help: "Links must be distinguishable without relying on color",
    description:
      "Ensure links are distinguished from surrounding text in a way that does not rely on color",
    criteria: ["1.4.1"],
  },
  "link-name": {
    help: "Links must have discernible text",
    description: "Ensure links have discernible text",
    criteria: ["2.4.4", "4.1.2"],
  },
  list: {
    help: "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
    description: "Ensure that lists are structured correctly",
    criteria: ["1.3.1"],
  },
  listitem: {
    help: "<li> elements must be contained in a <ul> or <ol>",
    description: "Ensure <li> elements are used semantically",
    criteria: ["1.3.1"],
  },
  marquee: {
    help: "<marquee> elements are deprecated and must not be used",
    description: "Ensure <marquee> elements are not used",
    criteria: ["2.2.2"],
  },
  "meta-refresh": {
    help: "Delayed refresh under 20 hours must not be used",
    description: 'Ensure <meta http-equiv="refresh"> is not used for delayed refresh',
    criteria: ["2.2.1"],
  },
  "meta-refresh-no-exceptions": {
    help: "Delayed refresh must not be used",
    description: 'Ensure <meta http-equiv="refresh"> is not used for delayed refresh',
    criteria: ["2.2.4", "3.2.5"],
  },
  "meta-viewport": {
    help: "Zooming and scaling must not be disabled",
    description: 'Ensure <meta name="viewport"> does not disable text scaling and zooming',
    criteria: ["1.4.4"],
  },
  "nested-interactive": {
    help: "Interactive controls must not be nested",
    description:
      "Ensure interactive controls are not nested as they are not always announced by screen readers or can cause focus problems for assistive technologies",
    criteria: ["4.1.2"],
  },
  "no-autoplay-audio": {
    help: "<video> or <audio> elements must not play automatically",
    description:
      "Ensure <video> or <audio> elements do not autoplay audio for more than 3 seconds without a control mechanism to stop or mute the audio",
    criteria: ["1.4.2"],
  },
  "object-alt": {
    help: "<object> elements must have alternative text",
    description: "Ensure <object> elements have alternative text",
    criteria: ["1.1.1"],
  },
  "p-as-heading": {
    help: "Styled <p> elements must not be used as headings",
    description:
      "Ensure bold, italic text and font-size is not used to style <p> elements as a heading",
    criteria: ["1.3.1"],
  },
  "role-img-alt": {
    help: '[role="img"] elements must have alternative text',
    description: 'Ensure [role="img"] elements have alternative text',
    criteria: ["1.1.1"],
  },
  "scrollable-region-focusable": {
    help: "Scrollable region must have keyboard access",
    description:
      "Ensure elements that have scrollable content are accessible by keyboard in Safari",
    criteria: ["2.1.1", "2.1.3"],
  },
  "select-name": {
    help: "Select element must have an accessible name",
    description: "Ensure select element has an accessible name",
    criteria: ["4.1.2"],
  },
  "server-side-image-map": {
    help: "Server-side image maps must not be used",
    description: "Ensure that server-side image maps are not used",
    criteria: ["2.1.1"],
  },
  "summary-name": {
    help: "Summary elements must have discernible text",
    description: "Ensure summary elements have discernible text",
    criteria: ["4.1.2"],
  },
  "svg-img-alt": {
    help: "<svg> elements with an img role must have alternative text",
    description:
      "Ensure <svg> elements with an img, graphics-document or graphics-symbol role have accessible text",
    criteria: ["1.1.1"],
  },
  "table-fake-caption": {
    help: "Data or header cells must not be used to give caption to a data table.",
    description: "Ensure that tables with a caption use the <caption> element.",
    criteria: ["1.3.1"],
  },
  "target-size": {
    help: "All touch targets must be 24px large, or leave sufficient space",
    description: "Ensure touch targets have sufficient size and space",
    criteria: ["2.5.8"],
  },
  "td-has-header": {
    help: "Non-empty <td> elements in larger <table> must have an associated table header",
    description:
      "Ensure that each non-empty data cell in a <table> larger than 3 by 3  has one or more table headers",
    criteria: ["1.3.1"],
  },
  "td-headers-attr": {
    help: "Table cell headers attributes must refer to other <th> elements in the same table",
    description:
      "Ensure that each cell in a table that uses the headers attribute refers only to other <th> elements in that table",
    criteria: ["1.3.1"],
  },
  "th-has-data-cells": {
    help: "Table headers in a data table must refer to data cells",
    description:
      "Ensure that <th> elements and elements with role=columnheader/rowheader have data cells they describe",
    criteria: ["1.3.1"],
  },
  "valid-lang": {
    help: "lang attribute must have a valid value",
    description: "Ensure lang attributes have valid values",
    criteria: ["3.1.2"],
  },
  "video-caption": {
    help: "<video> elements must have captions",
    description: "Ensure <video> elements have captions",
    criteria: ["1.2.2"],
  },
};
