/**
 * Regenerates `src/grounding/axe-rules.generated.ts` from the installed axe-core.
 *
 *   pnpm --filter @ally-fix/llm grounding:generate
 *
 * The rule catalogue is copied rather than read at runtime on purpose: the LLM
 * package must not depend on axe-core (it never runs a browser), and a checked-in
 * snapshot means the prompt is reviewable in a diff. `grounding.test.ts` fails
 * when the snapshot and the installed axe-core disagree, so an axe upgrade that
 * adds or renames a rule cannot silently leave the prompt describing the old one.
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const axe = require("axe-core") as {
  version: string;
  getRules: () => { ruleId: string; description: string; help: string; tags: string[] }[];
};

/** axe tags carry the criterion as "wcag111" (→ 1.1.1) or "wcag1410" (→ 1.4.10). */
function criteriaFromTags(tags: string[]): string[] {
  const found = new Set<string>();
  for (const tag of tags) {
    const match = /^wcag(\d)(\d)(\d+)$/.exec(tag);
    if (match) found.add(`${match[1]}.${match[2]}.${match[3]}`);
  }
  return [...found].sort();
}

const rules = axe
  .getRules()
  .map((rule) => ({
    id: rule.ruleId,
    help: rule.help,
    description: rule.description,
    criteria: criteriaFromTags(rule.tags),
  }))
  // Rules outside WCAG (best-practice checks) carry no criterion and get no
  // grounding block — better silence than an invented citation.
  .filter((rule) => rule.criteria.length > 0)
  .sort((a, b) => a.id.localeCompare(b.id));

const body = rules
  .map(
    (rule) =>
      `  ${JSON.stringify(rule.id)}: {\n` +
      `    help: ${JSON.stringify(rule.help)},\n` +
      `    description: ${JSON.stringify(rule.description)},\n` +
      `    criteria: [${rule.criteria.map((c) => JSON.stringify(c)).join(", ")}],\n` +
      `  },`,
  )
  .join("\n");

const file = `// Generated by scripts/generate-axe-rules.ts from axe-core ${axe.version}. Do not edit.
// Regenerate with: pnpm --filter @ally-fix/llm grounding:generate

/** What axe-core says about one rule, and which WCAG criteria it enforces. */
export interface AxeRuleFacts {
  /** axe's one-line statement of the requirement. */
  help: string;
  /** axe's longer description of what the rule checks. */
  description: string;
  /** WCAG success criteria this rule maps to, e.g. ["1.1.1"]. Never empty. */
  criteria: string[];
}

export const AXE_CORE_VERSION = ${JSON.stringify(axe.version)};

export const AXE_RULE_FACTS: Record<string, AxeRuleFacts> = {
${body}
};
`;

const out = fileURLToPath(new URL("../src/grounding/axe-rules.generated.ts", import.meta.url));
writeFileSync(out, file);
console.log(`Wrote ${rules.length} WCAG-mapped rules from axe-core ${axe.version} to ${out}`);
